- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="{{ ansible_host }}" --apiserver-cert-extra-sans="{{ ansible_host }}"  --node-name "{{ ansible_host }}" --pod-network-cidr=192.168.0.0/16

- name: Setup kubeconfig for automation user
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/automation/.kube
    - cp -i /etc/kubernetes/admin.conf /home/automation/.kube/config
    - chown automation:automation /home/automation/.kube/config

- name: download calico pod network
  become: false
  get_url:
    url: https://docs.projectcalico.org/manifests/calico.yaml
    dest: ~/calico.yaml
  
- name: Install calico pod network
  become: false
  command: "kubectl apply -f ~/calico.yaml"

- name: Generate join command
  become: false
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
